# Generated by Django 6.0.2 on 2026-03-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0004_congratulation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='Тэг')),
            ],
        ),
        migrations.AddField(
            model_name='birthday',
            name='tag',
            field=models.ManyToManyField(blank=True, help_text='Удерживайте Ctrl для выбора нескольких вариантов', to='birthday.tag', verbose_name='Тэги'),
        ),
    ]
